apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{prNumber}}
  namespace: {{namespace}}
spec:
  rules:
    - host: {{hostname}}
      http:
        paths:
          - path: /pr-{{prNumber}}-{{namespace}}/backend
            pathType: Prefix
            backend:
              service:
                name: {{service_name}}
                port:
                  number: 80